doctrine:
    dbal:
        # @see https://symfony.com/doc/6.2/doctrine/multiple_entity_managers.html
        connections:
            default:
                # IMPORTANT: You MUST configure your server version,
                # either here or in the DATABASE_URL env var (see .env file)
                url: '%env(resolve:DATABASE_URL)%'
            crawler:
                url: '%env(resolve:CRAWLER_DATABASE_URL)%'
        default_connection: default
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/App'
                        prefix: 'App\Entity\Main'
                        alias: Main
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
            customer:
                connection: crawler
                mappings:
                    Customer:
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Crawler'
                        prefix: 'App\Entity\Crawler'
                        alias: Crawler
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
